server:
  servlet:
    context-path: /wechat
  port: 80
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mooc?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.th.entity
